spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IslamHamada/petshop_sharedconfig
          username: ${GIT_USERNAME}
          password: ${GIT_ACCESSTOKEN}
          clone-on-start: true
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost:8081}/eureka
#      defaultZone: http://host.docker.internal:8081/eureka
